apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - image: gcr.io/jenkinsxio/jx-cli:3.0.773
          name: build-chart
          resources: {}
          script: |
            #!/usr/bin/env bash
            cd /workspace/source/deploy/helm
            make build
  podTemplate: {}
  timeout: 240h0m0s
status: {}
